/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'GitBuilding and GitHub Pages',
      link: {
        type: 'generated-index',
        description: '5 minutes to learn the most important GitBuilding and GitHub concepts.',
            },
      items: [
              'tutorial-basics-github/create-a-project-windows',
              'tutorial-basics-github/deploy-website-github'
             ]
    },
    {
      type: 'category',
      label: 'GitBuilding and GitLab Pages',
      link: {
        type: 'generated-index',
        description: '5 minutes to learn the most important GitBuilding and GitLab concepts.',
            },
      items: [
              'tutorial-basics-gitlab/create-a-project-windows',
              'tutorial-basics-gitlab/deploy-website-gitlab'
             ]
    },
    {
      type: 'category',
      label: 'GitBuilding - Extras',
      link: {
        type: 'generated-index',
            },
      items: [
              'tutorial-extras/examples'
             ]
    },
  ],

};

module.exports = sidebars;
